name: openmm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ambertools=23.6
  - annotated-types=0.7.0
  - anyio=4.4.0
  - archspec=0.2.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - astunparse=1.6.3
  - async-lru=2.0.4
  - attrs=23.2.0
  - Babel=2.14.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - boltons=24.0.0
  - Brotli=1.1.0
  - bson=0.5.9
  - cached-property=1.5.2
  - cachetools=5.3.3
  - certifi=2024.8.30
  - cffi=1.16.0
  - cftime=1.6.4
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.2.1
  - coverage=7.6.1
  - cycler=0.12.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - distro=1.9.0
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fasteners=0.19
  - fonttools=4.53.1
  - fqdn=1.5.1
  - freetype-py=2.3.0
  - frozendict=2.4.4
  - greenlet=3.0.3
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - idna=3.7
  - importlib_metadata=8.0.0
  - importlib_resources=6.4.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - ipywidgets=8.1.3
  - jax=0.4.27
  - jedi=0.19.1
  - Jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyterlab=4.2.3
  - kiwisolver=1.4.5
  - lightgbm=4.5.0
  - llvmlite=0.43.0
  - lxml=5.2.2
  - matplotlib=3.9.1
  - matplotlib-inline=0.1.7
  - MDAnalysis=2.7.0
  - mdtraj=1.10.0
  - mmtf-python=1.1.3
  - mrcfile=1.5.0
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - netCDF4=1.6.5
  - networkx=3.3
  - numba=0.60.0
  - numexpr=2.10.0
  - numpy=1.23.5
  - pandas=2.2.2
  - ParmEd=4.2.2
  - pdbfixer=1.9.0
  - pillow=10.3.0
  - pip
  - pip:
      - nest_asyncio==1.6.0
      - fastjsonschema==2.20.0
      #- gufe==0+unknown
      #- mpiplus==0+untagged.38.gfd8a5aa.dirty
      #- openff-amber-ff-ports==0+untagged.32.g809f411.dirty
      #- smirnoff99frosst==0+unknown
      #- conda-libmamba-solver=24.7.0
      #- conda_package_streaming=0.10.0
